<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-HGE39OB" name="testngPackage.firstTestngTest2" tests="6" failures="0" timestamp="2019-11-22T07:32:32 IST" time="1.043" errors="1">
  <testcase name="TestCase21" time="0.010" classname="testngPackage.firstTestngTest2"/>
  <testcase name="TestCase2" time="0.004" classname="testngPackage.firstTestngTest2"/>
  <testcase name="TestCase1" time="1.017" classname="testngPackage.firstTestngTest2">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method testngPackage.firstTestngTest2.TestCase1() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testngPackage.firstTestngTest2.TestCase1() didn't finish within the time-out 1000
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.signalAll(AbstractQueuedSynchronizer.java:1957)
at java.util.concurrent.ThreadPoolExecutor.tryTerminate(ThreadPoolExecutor.java:716)
at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1014)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- TestCase1 -->
  <testcase name="TestCase4" time="0.005" classname="testngPackage.firstTestngTest2"/>
  <testcase name="TestCase4" time="0.007" classname="testngPackage.firstTestngTest2"/>
  <testcase name="TestCase3" time="0.000" classname="testngPackage.firstTestngTest2">
    <skipped/>
  </testcase> <!-- TestCase3 -->
</testsuite> <!-- testngPackage.firstTestngTest2 -->
